apiVersion: apps/v1
kind: Deployment
metadata:
  name: abac-engine
  namespace: medrex-services
  labels:
    app: abac-engine
    component: rbac-system
    tier: attribute-engine
spec:
  replicas: 3
  selector:
    matchLabels:
      app: abac-engine
  template:
    metadata:
      labels:
        app: abac-engine
        component: rbac-system
        tier: attribute-engine
    spec:
      containers:
      - name: abac-engine
        image: medrex/abac-engine:latest
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8081
          name: metrics
        - containerPort: 9090
          name: grpc
        env:
        - name: PORT
          value: "8080"
        - name: METRICS_PORT
          value: "8081"
        - name: GRPC_PORT
          value: "9090"
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: medrex-config
              key: database_host
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: medrex-config
              key: database_port
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: medrex-config
              key: database_name
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: medrex-secrets
              key: database_username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: medrex-secrets
              key: database_password
        - name: ABAC_EVALUATION_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: rbac-config
              key: abac_evaluation_timeout
        - name: ATTRIBUTE_CACHE_SIZE
          valueFrom:
            configMapKeyRef:
              name: rbac-config
              key: attribute_cache_size
        - name: CERTIFICATE_MANAGER_ENDPOINT
          value: "certificate-manager-service.medrex-services.svc.cluster.local:9090"
        - name: FABRIC_NETWORK_CONFIG
          valueFrom:
            configMapKeyRef:
              name: rbac-config
              key: fabric_network_config
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: medrex-config
              key: log_level
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: medrex-config
              key: environment
        volumeMounts:
        - name: fabric-crypto
          mountPath: /etc/hyperledger/fabric
          readOnly: true
        - name: abac-policies
          mountPath: /etc/abac/policies
          readOnly: true
        - name: attribute-cache
          mountPath: /var/cache/abac
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      volumes:
      - name: fabric-crypto
        secret:
          secretName: fabric-crypto-material
      - name: abac-policies
        configMap:
          name: abac-policies
      - name: attribute-cache
        emptyDir:
          sizeLimit: 512Mi
      securityContext:
        fsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: abac-engine-service
  namespace: medrex-services
  labels:
    app: abac-engine
    component: rbac-system
spec:
  selector:
    app: abac-engine
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: metrics
    port: 8081
    targetPort: 8081
    protocol: TCP
  - name: grpc
    port: 9090
    targetPort: 9090
    protocol: TCP
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: abac-engine-hpa
  namespace: medrex-services
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: abac-engine
  minReplicas: 3
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60