apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbe-policy-manager
  namespace: medrex-services
  labels:
    app: sbe-policy-manager
    component: rbac-system
    tier: policy-engine
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sbe-policy-manager
  template:
    metadata:
      labels:
        app: sbe-policy-manager
        component: rbac-system
        tier: policy-engine
    spec:
      containers:
      - name: sbe-policy-manager
        image: medrex/sbe-policy-manager:latest
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8081
          name: metrics
        - containerPort: 9090
          name: grpc
        env:
        - name: PORT
          value: "8080"
        - name: METRICS_PORT
          value: "8081"
        - name: GRPC_PORT
          value: "9090"
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: medrex-config
              key: database_host
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: medrex-config
              key: database_port
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: medrex-config
              key: database_name
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: medrex-secrets
              key: database_username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: medrex-secrets
              key: database_password
        - name: FABRIC_NETWORK_CONFIG
          valueFrom:
            configMapKeyRef:
              name: rbac-config
              key: fabric_network_config
        - name: SBE_POLICY_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: rbac-config
              key: sbe_policy_timeout
        - name: SUPERVISION_WORKFLOW_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: rbac-config
              key: supervision_workflow_timeout
        - name: EMERGENCY_OVERRIDE_ENABLED
          valueFrom:
            configMapKeyRef:
              name: rbac-config
              key: emergency_override_enabled
        - name: CERTIFICATE_MANAGER_ENDPOINT
          value: "certificate-manager-service.medrex-services.svc.cluster.local:9090"
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: medrex-config
              key: log_level
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: medrex-config
              key: environment
        volumeMounts:
        - name: fabric-crypto
          mountPath: /etc/hyperledger/fabric
          readOnly: true
        - name: sbe-policies
          mountPath: /etc/sbe/policies
          readOnly: true
        - name: workflow-state
          mountPath: /var/state/sbe
        resources:
          requests:
            memory: "768Mi"
            cpu: "300m"
          limits:
            memory: "1.5Gi"
            cpu: "750m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      volumes:
      - name: fabric-crypto
        secret:
          secretName: fabric-crypto-material
      - name: sbe-policies
        configMap:
          name: sbe-policies
      - name: workflow-state
        persistentVolumeClaim:
          claimName: sbe-workflow-state-pvc
      securityContext:
        fsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: sbe-policy-manager-service
  namespace: medrex-services
  labels:
    app: sbe-policy-manager
    component: rbac-system
spec:
  selector:
    app: sbe-policy-manager
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: metrics
    port: 8081
    targetPort: 8081
    protocol: TCP
  - name: grpc
    port: 9090
    targetPort: 9090
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sbe-workflow-state-pvc
  namespace: medrex-services
  labels:
    app: sbe-policy-manager
    component: rbac-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sbe-policy-manager-hpa
  namespace: medrex-services
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sbe-policy-manager
  minReplicas: 3
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60