apiVersion: apps/v1
kind: Deployment
metadata:
  name: certificate-manager
  namespace: medrex-services
  labels:
    app: certificate-manager
    component: rbac-system
    tier: identity-management
spec:
  replicas: 3
  selector:
    matchLabels:
      app: certificate-manager
  template:
    metadata:
      labels:
        app: certificate-manager
        component: rbac-system
        tier: identity-management
    spec:
      containers:
      - name: certificate-manager
        image: medrex/certificate-manager:latest
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8081
          name: metrics
        - containerPort: 9090
          name: grpc
        env:
        - name: PORT
          value: "8080"
        - name: METRICS_PORT
          value: "8081"
        - name: GRPC_PORT
          value: "9090"
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: medrex-config
              key: database_host
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: medrex-config
              key: database_port
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: medrex-config
              key: database_name
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: medrex-secrets
              key: database_username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: medrex-secrets
              key: database_password
        - name: FABRIC_CA_HOSPITAL_URL
          valueFrom:
            configMapKeyRef:
              name: rbac-config
              key: fabric_ca_hospital_url
        - name: FABRIC_CA_PHARMACY_URL
          valueFrom:
            configMapKeyRef:
              name: rbac-config
              key: fabric_ca_pharmacy_url
        - name: FABRIC_CA_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: fabric-ca-secrets
              key: admin_username
        - name: FABRIC_CA_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fabric-ca-secrets
              key: admin_password
        - name: CERTIFICATE_VALIDITY_PERIOD
          valueFrom:
            configMapKeyRef:
              name: rbac-config
              key: certificate_validity_period
        - name: ATTRIBUTE_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: rbac-secrets
              key: attribute_encryption_key
        - name: HSM_API_KEY
          valueFrom:
            secretKeyRef:
              name: medrex-secrets
              key: hsm_api_key
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: medrex-config
              key: log_level
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: medrex-config
              key: environment
        volumeMounts:
        - name: fabric-crypto
          mountPath: /etc/hyperledger/fabric
          readOnly: true
        - name: ca-certificates
          mountPath: /etc/ssl/ca-certificates
          readOnly: true
        - name: certificate-store
          mountPath: /var/store/certificates
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      volumes:
      - name: fabric-crypto
        secret:
          secretName: fabric-crypto-material
      - name: ca-certificates
        secret:
          secretName: fabric-ca-certificates
      - name: certificate-store
        persistentVolumeClaim:
          claimName: certificate-store-pvc
      securityContext:
        fsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: certificate-manager-service
  namespace: medrex-services
  labels:
    app: certificate-manager
    component: rbac-system
spec:
  selector:
    app: certificate-manager
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: metrics
    port: 8081
    targetPort: 8081
    protocol: TCP
  - name: grpc
    port: 9090
    targetPort: 9090
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: certificate-store-pvc
  namespace: medrex-services
  labels:
    app: certificate-manager
    component: rbac-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: fast-ssd
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: certificate-manager-hpa
  namespace: medrex-services
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: certificate-manager
  minReplicas: 3
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60